### ISSUE TITLE
Error: Cannot find module 'core-js/fn/string/pad-start'

### ISSUE THREAD

**Issue by bt-altius** [manuelbieh/react-ssr-setup#34]
I liked your approach and setup but was confronted with a build error; details below:

**OS:** macOS Mojave 10.14
**NPM:** 6.4.1
**Node:** 10.13.0

**Repro steps:**
1. clone repo
2. `npm i`
3. `npm start`

**Console output:**
Note: I removed the absolute path to the directory `react-ssr-setup`.
```
> react-ssr-setup@2.0.2 start ./react-ssr-setup
> cross-env NODE_ENV=development node scripts/start.js

[2018-11-30T20:15:49.130Z] [client] Compiling
[2018-11-30T20:15:49.155Z] [server] Compiling
Hash: 1fa189826e0428df7eea
Version: webpack 4.26.1
Time: 3884ms
Built at: 11/30/2018 12:15:53 PM
    Asset    Size  Chunks             Chunk Names
server.js  89 KiB  server  [emitted]  server
Entrypoint server = server.js
[0] multi ./node_modules/@babel/polyfill/lib/index.js ./src/server/index.js 40 bytes {server} [built]
[./config/paths.js] 574 bytes {server} [built]
[./node_modules/@babel/polyfill/lib/index.js] 893 bytes {server} [built]
[./src/server/index.js] 1.71 KiB {server} [built]
[./src/server/render.js] 885 bytes {server} [built]
[./src/shared/store/index.js] 1.46 KiB {server} [built]
[body-parser] external "body-parser" 42 bytes {server} [built]
[chalk] external "chalk" 42 bytes {server} [built]
[core-js/es6] external "core-js/es6" 42 bytes {server} [built]
[core-js/fn/array/includes] external "core-js/fn/array/includes" 42 bytes {server} [built]
[core-js/fn/object/entries] external "core-js/fn/object/entries" 42 bytes {server} [built]
[core-js/fn/object/get-own-property-descriptors] external "core-js/fn/object/get-own-property-descriptors" 42 bytes {server} [built]
[core-js/fn/object/values] external "core-js/fn/object/values" 42 bytes {server} [built]
[core-js/fn/promise/finally] external "core-js/fn/promise/finally" 42 bytes {server} [built]
[core-js/fn/string/pad-end] external "core-js/fn/string/pad-end" 42 bytes {server} [built]
    + 34 hidden modules
webpack built client 14b9a97258757ac60758 in 5157ms
ℹ ｢wdm｣: Time: 5157ms
Built at: 11/30/2018 12:15:54 PM
                    Asset       Size  Chunks                    Chunk Names
assets/react.9a28da9f.svg   7.72 KiB          [emitted]
               bundle.css   18.8 KiB  bundle  [emitted]         bundle
                bundle.js    136 KiB  bundle  [emitted]         bundle
            manifest.json  270 bytes          [emitted]
 vendor.c63ffa3b.chunk.js   4.34 MiB  vendor  [emitted]  [big]  vendor
Entrypoint bundle [big] = vendor.c63ffa3b.chunk.js bundle.css bundle.js
Child mini-css-extract-plugin node_modules/css-loader/index.js??ref--4-oneOf-1-2!node_modules/postcss-loader/src/index.js??ref--4-oneOf-1-3!src/shared/App.module.css:
    Entrypoint mini-css-extract-plugin = *
Child mini-css-extract-plugin node_modules/css-loader/index.js??ref--4-oneOf-1-2!node_modules/postcss-loader/src/index.js??ref--4-oneOf-1-3!src/shared/components/Features/Features.module.css:
    Entrypoint mini-css-extract-plugin = *
ℹ ｢wdm｣: Compiled successfully.
internal/modules/cjs/loader.js:582
    throw err;
    ^

Error: Cannot find module 'core-js/fn/string/pad-start'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at eval (webpack:///external_%22core-js/fn/string/pad-start%22?:1:18)
    at Object.core-js/fn/string/pad-start (./react-ssr-setup/build/server/server.js:1083:1)
    at __webpack_require__ (./react-ssr-setup/build/server/server.js:683:30)
    at fn (./react-ssr-setup/build/server/server.js:60:20)
    at eval (webpack:///./node_modules/@babel/polyfill/lib/index.js?:7:1)
    at Object../node_modules/@babel/polyfill/lib/index.js (./react-ssr-setup/build/server/server.js:774:1)
```

**Comment by manuelbieh** [comment]
Works for me with a freshly cloned repo with Node 10.11.0 and npm 6.4.1. Maybe some npm/yarn hickups? I'd suggest to remove node_modules (`rm -rf node_modules`) and re-install them using `yarn` (`npm i` should be fine as well).

**Comment by lukeliasi** [comment]
` npm i -D core-js ` fixed it for me.

**Comment by bt-altius** [comment]
@manuelbieh That could be; I tried that and got the same result. But, the simple solution from @lukeliasi allowed that core-js modules to be resolved correctly.

**Comment by manuelbieh** [comment]
`core-js` is causing some issues here indeed. I added it to the devDeps now and it seems to work. Unless you upgrade it to version ^3.0.0. So I will stick with ^2.0.0 for the moment and see if I can find a fix later. Issue should be fixed. Feel free to re-open if not!
