### ISSUE TITLE
how do use ant.design UI in this project？

### ISSUE THREAD

**Issue by zkeyword** [manuelbieh/react-ssr-setup#76]
I try write it in babal.config.js:

`
['import', {
            'libraryName': 'antd',
            'libraryDirectory': 'lib',
            'style': 'css'
        }],
`

and use:
`import { Modal } from 'antd'`

but, throw error:

`
    /Users/zkeyword/Documents/ssr/node_modules/antd/lib/style/index.css:7
    body {
        ^

    SyntaxError: Unexpected token {
        at Module._compile (internal/modules/cjs/loader.js:718:23)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
        at Module.load (internal/modules/cjs/loader.js:641:32)
        at Function.Module._load (internal/modules/cjs/loader.js:556:12)
        at Module.require (internal/modules/cjs/loader.js:681:19)

`

**Comment by TGMorais** [comment]
Hello!

I'm having a similar issue, I'm trying out the project and I've installed an npm package that imports '.css' files into it's own files.
However the server build throws an error complaining about Unexpected token in the css file.
It seems to be that there is something off in the server webpack config, but still trying to find out.
